spring.application.name=travel-mate

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=travel_mate;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jackson.date-format=dd-MM-yyyy
spring.jackson.serialization.write-dates-as-timestamps=false

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngothang.learn@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
